version: 2
jobs:
  api_build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: cd api/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew clean ktlint test
      - store_artifacts:
          path: build/distributions
          destination: jars
      - store_artifacts:
          path: build/resources
          destination: resources
  frontend_build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: cd frontend/
      - run: yarn test
      - run: docker build -t quay.io/nick96/cub-tracking-frontend:${CIRCLE_SHA1} -f docker/Dockerfile .
      - run: ./docker/smoke_test.sh


workflows:
  version: 2
  test-build:
    jobs:
      - api_build
      - frontend_build
