version: 2.1

commands:
  install_docker_compose:
    description: Install Docker Compose
    steps:
      - run:
          name: Install pre-requisites
          command: apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
      - run:
          name: Install docker-compose
          command: pip install docker-compose

  api_run:
    description: Run a command using api/ as the working directory
    parameters:
      description:
        type: string
      command:
        type: string
    steps:
      - run:
          command: << parameters.command >>
          working_directory: api

  frontend_run:
    description: Run a command using frontend/ as the working directory
    parameters:
      description:
        type: string
      command:
        type: string
    steps:
      - run:
          command: << parameters.command >>
          working_directory: frontend

  push_to_quayio:
    description: Push a docker image to quay.io
    parameters:
      container_name:
        type: string
      tag:
        type: string
      branch:
        type: string
    steps:
      - run:
          name: Push api Docker image to quay.io
          command: |
            if [ "${CIRCLE_BRANCH}" == "<< parameters.branch >>" ]
            then
              docker login -u "${QUAYIO_USR}" -p "${QUAYIO_PSW}"
              docker tag "<< parameters.container_name >>" "quay.io/nick96/<< parameters.tag >>"
              docker push "<< parameters.tag >>"
            fi


jobs:
  api_build_test:
    docker:
      - image: docker:18.09.6-git
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_compose
      - api_run:
          description: Build test image and run unit tests
          command: docker build -t api-testing -f docker/Dockerfile --target test .
      - api_run:
          description: Run integration tests
          command: docker-compose -f docker/docker-compose.test.yml up
      - api_run:
          command: docker build -t cub-tracking-api -f docker/Dockerfile .
      - push_to_quayio:
          container_name: cub-tracking-api
          tag: cub-tracking-api:${CIRCLE_SHA1}
          branch: master

  frontend_build_test:
    docker:
      - image: docker:18.09.6-g
    steps:
      - checkout
      - setup_remote_docker
      - install_docker_compose
      - frontend_run:
          description: Build test image and run unit tests
          command: docker build -t frontend-testing -f docker/Dockerfile --target test .
      - frontend_run:
          description: Run integration tests
          command: docker-compse -f docker/docker-compose.test.yml up
      - frontend_run:
          description: Build production image
          command: docker build -t cub-tracking-frontend -f docker/Dockerfile .
      - run:
          name: Install bash for smoke tests
          command: apk add bash
      - frontend_run:
          command: ./docker/smoke_test.sh
      - push_to_quayio:
          container_name: cub-tracking-frontend
          tag: cub-tracking-frontend:${CIRCLE_SHA1}
          branch: master

workflows:
  version: 2
  test-build:
    jobs:
      - api_build_test
      - frontend_build_test
