version: 2
jobs:
  api_build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Clean lint and test
          command: ./gradlew clean ktlint test
          working_directory: api/
      - store_artifacts:
          path: api/build/distributions
          destination: jars
      - store_artifacts:
          path: api/build/resources
          destination: resources
  frontend_build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
          working_directory: frontend
      - run:
          name: Run tests
          command: yarn test
          working_directory: frontend
      - run:
          name: Build docker image
          command: docker build -t quay.io/nick96/cub-tracking-frontend:${CIRCLE_SHA1} -f docker/Dockerfile .
          working_directory: frontend
      - run:
          name: Run smoke tests
          command: ./docker/smoke_test.sh
          working_directory: frontend


workflows:
  version: 2
  test-build:
    jobs:
      - api_build
      - frontend_build
